### Exercice 3

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [ ]:


X_train = [['Python'], ['Java'], ['Java'], ['C++']]

In [2]:
encoder = OneHotEncoder(handle_unknown='ignore')
encoder.fit(X_train)

X_train_encoded = encoder.transform(X_train).toarray()

categories = encoder.categories_[0]
X_train_df = pd.DataFrame(X_train_encoded, columns=categories)

print("Question 1\n")
X_train_df.astype(int)

Question 1

   C++  Java  Python
0    0     0       1
1    0     1       0
2    0     1       0
3    1     0       0

In [3]:
X_test = [['Python'], ['Java'], ['C'], ['C++']]

In [4]:
X_test_encoded = encoder.transform(X_test)
X_test_df = pd.DataFrame(X_test_encoded.toarray(), columns=categories)

print("Question 2\n")
X_test_df.astype(int)

Question 2

   C++  Java  Python
0    0     0       1
1    0     1       0
2    0     0       0
3    1     0       0